// Preset strategy configs — these are DATA, not engine code. Every field is
// consumed by the universal engine; no strategy is hardcoded.
import type { StrategyConfig } from "./types";

export const STRATEGY_PRESETS: Record<string, StrategyConfig> = {
  // ── Phase 1 additions ──────────────────────────────────────────────

  pdh_pdl_sweep_1m: {
    strategyId: "pdh-pdl-sweep-1m",
    strategyName: "PDH/PDL Liquidity Sweep (1:4)",
    direction: "both",
    session: { blockWeekend: true },
    trend: {},
    volatility: { atrPercentileMin: 20, atrPercentileMax: 95 },
    setup: { kind: "pdh_pdl_sweep", breakBufferPct: 0.02 },
    confirmation: { requireClose: true, minBodyPct: 35 },
    entry: { model: { kind: "limit", pullbackPct: 0.02 }, expiryBars: 3 },
    stop: { kind: "sweep_extreme", bufferPct: 0.02 },
    targets: {
      legs: [{ kind: "rr", value: 4, sizePct: 100 }],
      moveToBreakEvenAtR: 1,
      trailAfterR: 2,
      trailStepR: 0.5,
    },
    management: { maxDailyTrades: 2, maxAttemptsPerSweep: 1 },
    invalidation: { maxDelayBars: 3 },
    risk: { riskPerTradeUsd: 100 },
  },

  london_orb: {
    strategyId: "london-orb",
    strategyName: "London ORB Breakout (1:4)",
    direction: "both",
    session: { allowedSessions: ["london", "london_ny_overlap"], blockWeekend: true, blockHoliday: true },
    trend: { adxMin: 18 },
    volatility: { atrPercentileMin: 30, atrPercentileMax: 95 },
    setup: { kind: "opening_range_break", breakBufferPct: 0.04 },
    confirmation: { requireClose: true, minBodyPct: 50, minAtrMultiple: 0.25 },
    entry: { model: { kind: "stop", breakoutBufferPct: 0.02 }, expiryBars: 4 },
    stop: { kind: "opposite_range" },
    targets: {
      legs: [{ kind: "rr", value: 4, sizePct: 100 }],
      moveToBreakEvenAtR: 1,
      trailAfterR: 2,
      trailStepR: 0.5,
    },
    management: { maxDailyTrades: 1, timeStopBars: 30 },
    invalidation: { maxDelayBars: 4, invalidateOnSessionEnd: true, invalidateOnStructureFlip: true },
    risk: { riskPerTradeUsd: 100 },
  },

  vwap_mean_revert: {
    strategyId: "vwap-mean-revert",
    strategyName: "VWAP Mean Reversion (1:4)",
    direction: "both",
    session: { blockWeekend: true },
    trend: { adxMax: 24 },
    volatility: { atrPercentileMin: 10, atrPercentileMax: 80 },
    regime: { allowed: ["range_calm", "range_volatile"] },
    setup: { kind: "bb_zscore_fade", bbPeriod: 20, bbSigma: 2.0 },
    confirmation: { requireClose: true },
    entry: { model: { kind: "limit", pullbackPct: 0.02 }, expiryBars: 3 },
    stop: { kind: "atr", multiple: 1.2 },
    targets: {
      legs: [{ kind: "rr", value: 4, sizePct: 100 }],
      moveToBreakEvenAtR: 1,
      trailAfterR: 2,
      trailStepR: 0.5,
    },
    management: { maxDailyTrades: 3, timeStopBars: 16 },
    invalidation: { maxDelayBars: 3 },
    risk: { riskPerTradeUsd: 100 },
  },

  turtle_s1: {
    strategyId: "turtle-s1",
    strategyName: "Turtle Donchian 20/10",
    direction: "both",
    session: { blockWeekend: false },
    trend: {},
    volatility: { atrPercentileMin: 20 },
    regime: { allowed: ["trend_strong", "trend_weak"] },
    setup: { kind: "donchian_break", donchianLookback: 20, breakBufferPct: 0.05 },
    confirmation: { requireClose: true },
    entry: { model: { kind: "stop", breakoutBufferPct: 0.02 }, expiryBars: 3 },
    stop: { kind: "atr", multiple: 2 },
    targets: {
      legs: [{ kind: "atr_multiple", value: 4, sizePct: 50 }, { kind: "atr_multiple", value: 8, sizePct: 50 }],
      moveToBreakEvenAtR: 1.5,
      trailAfterR: 2,
      trailStepR: 1,
    },
    management: { maxDailyTrades: 2 },
    invalidation: { maxDelayBars: 3 },
    risk: { riskPerTradeUsd: 100 },
  },
  turtle_s2: {
    strategyId: "turtle-s2",
    strategyName: "Turtle Donchian 55/20",
    direction: "both",
    session: {},
    trend: {},
    volatility: {},
    regime: { allowed: ["trend_strong"] },
    hmm: { blocked: ["hmm_choppy"] },
    setup: { kind: "donchian_break", donchianLookback: 55, breakBufferPct: 0.05 },
    confirmation: { requireClose: true },
    entry: { model: { kind: "stop", breakoutBufferPct: 0.02 }, expiryBars: 3 },
    stop: { kind: "atr", multiple: 2 },
    targets: {
      legs: [{ kind: "atr_multiple", value: 6, sizePct: 50 }, { kind: "atr_multiple", value: 12, sizePct: 50 }],
      moveToBreakEvenAtR: 2,
      trailAfterR: 3,
      trailStepR: 1.5,
    },
    management: { maxDailyTrades: 1 },
    invalidation: { maxDelayBars: 3 },
    risk: { riskPerTradeUsd: 100 },
  },
  supertrend_trend: {
    strategyId: "supertrend-trend",
    strategyName: "SuperTrend Flip + EMA200",
    direction: "both",
    session: {},
    trend: { emaAlignment: { above: [200] }, adxMin: 25 },
    volatility: { atrPercentileMin: 30 },
    regime: { allowed: ["trend_strong"] },
    hmm: { blocked: ["hmm_choppy"] },
    setup: { kind: "supertrend_flip", supertrendPeriod: 10, supertrendMultiplier: 3 },
    confirmation: { requireClose: true },
    entry: { model: { kind: "market" } },
    stop: { kind: "atr", multiple: 2 },
    targets: {
      legs: [{ kind: "atr_multiple", value: 3, sizePct: 50 }, { kind: "atr_multiple", value: 6, sizePct: 50 }],
      moveToBreakEvenAtR: 1,
      trailAfterR: 1.5,
      trailStepR: 0.5,
    },
    management: { maxDailyTrades: 3 },
    invalidation: { maxDelayBars: 2 },
    risk: { riskPerTradeUsd: 100 },
  },
  rsi2_connors: {
    strategyId: "rsi2-connors",
    strategyName: "Connors RSI-2 Reversal",
    direction: "both",
    session: {},
    trend: { emaAlignment: { above: [200] } }, // long-only bias in bull regime via ema filter
    volatility: { atrPercentileMax: 70 },
    regime: { allowed: ["range_calm", "range_volatile"] },
    setup: { kind: "rsi_extreme", rsiPeriod: 2, rsiOversold: 10, rsiOverbought: 90 },
    confirmation: {},
    entry: { model: { kind: "market" } },
    stop: { kind: "atr", multiple: 1.5 },
    targets: { legs: [{ kind: "rr", value: 1, sizePct: 100 }] },
    management: { maxDailyTrades: 4, timeStopBars: 8 },
    invalidation: { maxDelayBars: 2 },
    risk: { riskPerTradeUsd: 100 },
  },
  bb_zscore_fade: {
    strategyId: "bb-zscore-fade",
    strategyName: "Bollinger Z-Score Fade (ADX<20)",
    direction: "both",
    session: {},
    trend: { adxMax: 20 },
    volatility: { atrPercentileMin: 10, atrPercentileMax: 70 },
    regime: { allowed: ["range_calm"] },
    hmm: { allowed: ["hmm_choppy"] },
    setup: { kind: "bb_zscore_fade", bbPeriod: 20, bbSigma: 2.5 },
    confirmation: {},
    entry: { model: { kind: "market" } },
    stop: { kind: "atr", multiple: 1.2 },
    targets: { legs: [{ kind: "rr", value: 1.5, sizePct: 100 }] },
    management: { maxDailyTrades: 4, timeStopBars: 12 },
    invalidation: { maxDelayBars: 2 },
    risk: { riskPerTradeUsd: 100 },
  },
  liquidity_sweep_long: {
    strategyId: "liquidity-sweep-long",
    strategyName: "Liquidity Sweep Long (1:4)",
    direction: "long",
    session: { blockWeekend: true },
    trend: {},
    volatility: { atrPercentileMin: 20, atrPercentileMax: 95 },
    setup: { kind: "liquidity_sweep", breakBufferPct: 0.02 },
    confirmation: { requireClose: true, minBodyPct: 35 },
    entry: { model: { kind: "limit", pullbackPct: 0.02 }, expiryBars: 3 },
    stop: { kind: "sweep_extreme", bufferPct: 0.02 },
    targets: {
      legs: [{ kind: "rr", value: 4, sizePct: 100 }],
      moveToBreakEvenAtR: 1,
      trailAfterR: 2,
      trailStepR: 0.5,
    },
    management: { maxDailyTrades: 2, maxAttemptsPerSweep: 1 },
    invalidation: { maxDelayBars: 3 },
    risk: { riskPerTradeUsd: 100 },
  },
  liquidity_sweep_short: {
    strategyId: "liquidity-sweep-short",
    strategyName: "Liquidity Sweep Short (1:4)",
    direction: "short",
    session: { blockWeekend: true },
    trend: {},
    volatility: { atrPercentileMin: 20, atrPercentileMax: 95 },
    setup: { kind: "liquidity_sweep", breakBufferPct: 0.02 },
    confirmation: { requireClose: true, minBodyPct: 35 },
    entry: { model: { kind: "limit", pullbackPct: 0.02 }, expiryBars: 3 },
    stop: { kind: "sweep_extreme", bufferPct: 0.02 },
    targets: {
      legs: [{ kind: "rr", value: 4, sizePct: 100 }],
      moveToBreakEvenAtR: 1,
      trailAfterR: 2,
      trailStepR: 0.5,
    },
    management: { maxDailyTrades: 2, maxAttemptsPerSweep: 1 },
    invalidation: { maxDelayBars: 3 },
    risk: { riskPerTradeUsd: 100 },
  },
  london_orb_xau_strict: {
    strategyId: "london-orb-xau-strict",
    strategyName: "XAU London ORB (VWAP + ADX filter)",
    direction: "both",
    session: { allowedSessions: ["london", "london_ny_overlap"], blockWeekend: true, blockHoliday: true },
    trend: { adxMin: 22, vwapSide: "above" },
    volatility: { atrPercentileMin: 40, atrPercentileMax: 95 },
    setup: { kind: "opening_range_break", breakBufferPct: 0.05 },
    confirmation: { requireClose: true, minBodyPct: 55, minAtrMultiple: 0.35 },
    entry: { model: { kind: "stop", breakoutBufferPct: 0.03 }, expiryBars: 4 },
    stop: { kind: "opposite_range" },
    targets: {
      legs: [{ kind: "rr", value: 1, sizePct: 40 }, { kind: "rr", value: 3, sizePct: 60 }],
      moveToBreakEvenAtR: 1,
      trailAfterR: 2,
      trailStepR: 0.5,
    },
    management: { maxDailyTrades: 1, timeStopBars: 30 },
    invalidation: { maxDelayBars: 4, invalidateOnSessionEnd: true, invalidateOnStructureFlip: true },
    risk: { riskPerTradeUsd: 100 },
  },
  // ── Phase 3: Funding-Rate Carry (Perp BTC) ────────────────────────
  // Fades extreme funding within the last 30-45 min before settlement.
  // Direction is enforced at runtime by `checkFundingFadeGate` in tick.server.ts.
  funding_fade_btc: {
    strategyId: "funding-fade-btc",
    strategyName: "Funding-Rate Fade (BTC Perp)",
    direction: "both",
    session: {},
    trend: { adxMax: 25 },
    volatility: { atrPercentileMin: 10, atrPercentileMax: 80 },
    setup: { kind: "bb_zscore_fade", bbPeriod: 20, bbSigma: 2.0 },
    confirmation: {},
    entry: { model: { kind: "limit", pullbackPct: 0.05 }, expiryBars: 4 },
    stop: { kind: "atr", multiple: 1.2 },
    targets: {
      legs: [{ kind: "rr", value: 1, sizePct: 60 }, { kind: "rr", value: 2, sizePct: 40 }],
      moveToBreakEvenAtR: 0.8,
    },
    management: { maxDailyTrades: 3, timeStopBars: 10 },
    invalidation: { maxDelayBars: 3 },
    risk: { riskPerTradeUsd: 100 },
  },
};

export type StrategyPresetId = keyof typeof STRATEGY_PRESETS;


