// Trade Intelligence — row <-> record mappers.
// Single source of truth for camelCase TradeRecord <-> snake_case DB row.
// Client-safe (pure), so any *.functions.ts handler can dynamic-import it
// without violating server-fn split rules.

import type { TradeRecord } from "./types";

export function recordToRow(r: TradeRecord) {
  return {
    trade_id: r.tradeId,
    strategy_id: r.strategyId,
    strategy_version: r.strategyVersion,
    symbol: r.symbol,
    timeframe: r.timeframe,
    direction: r.direction,
    trade_type: r.tradeType,
    entry_type: r.entryType,
    stop_type: r.stopType,
    target_type: r.targetType,
    status: r.status,
    session: r.session,
    signal_time: r.signalTime ? new Date(r.signalTime).toISOString() : null,
    order_time: r.orderTime ? new Date(r.orderTime).toISOString() : null,
    fill_time: r.fillTime ? new Date(r.fillTime).toISOString() : null,
    entry_time: new Date(r.entryTime).toISOString(),
    exit_time: new Date(r.exitTime).toISOString(),
    weekday: r.weekday, week_number: r.weekNumber, month: r.month,
    quarter: r.quarter, year: r.year,
    entry_price: r.entryPrice, fill_price: r.fillPrice, exit_price: r.exitPrice,
    stop_price: r.stopPrice, target_price: r.targetPrice,
    position_size: r.positionSize, risk_usd: r.riskUsd, risk_pct: r.riskPct,
    actual_rr: r.actualRr, gross_pnl: r.grossPnl, net_pnl: r.netPnl,
    pnl_pct: r.pnlPct, pnl_r: r.pnlR, mae: r.mae, mfe: r.mfe,
    fees: r.fees, commission: r.commission, slippage: r.slippage,
    spread_cost: r.spreadCost,
    holding_bars: r.holdingBars, duration_ms: r.durationMs, exit_reason: r.exitReason,
    price: r.price, risk: r.risk, performance: r.performance, duration: r.duration,
    volatility: r.volatility, trend: r.trend, structure: r.structure,
    liquidity: r.liquidity, smart_money: r.smartMoney, volume_profile: r.volumeProfile,
    breakout: r.breakout, entry_quality: r.entryQuality, stop: r.stop, target: r.target,
    filters: r.filters, news: r.news, regime: r.regime, custom: r.custom,
    tags: r.tags, raw: r.raw,
  };
}

export function rowToRecord(row: Record<string, unknown>): TradeRecord {
  const toMs = (v: unknown) => (v ? new Date(String(v)).getTime() : null);
  return {
    tradeId: String(row.trade_id),
    strategyId: String(row.strategy_id),
    strategyVersion: row.strategy_version as string | null,
    symbol: String(row.symbol),
    timeframe: row.timeframe as string | null,
    direction: row.direction as "long" | "short",
    tradeType: row.trade_type as string | null,
    entryType: row.entry_type as string | null,
    stopType: row.stop_type as string | null,
    targetType: row.target_type as string | null,
    status: row.status as "closed" | "open" | "cancelled",
    session: row.session as string | null,
    signalTime: toMs(row.signal_time),
    orderTime: toMs(row.order_time),
    fillTime: toMs(row.fill_time),
    entryTime: toMs(row.entry_time) ?? 0,
    exitTime: toMs(row.exit_time) ?? 0,
    weekday: row.weekday as number | null,
    weekNumber: row.week_number as number | null,
    month: row.month as number | null,
    quarter: row.quarter as number | null,
    year: row.year as number | null,
    entryPrice: Number(row.entry_price),
    fillPrice: row.fill_price as number | null,
    exitPrice: Number(row.exit_price),
    stopPrice: row.stop_price as number | null,
    targetPrice: row.target_price as number | null,
    positionSize: row.position_size as number | null,
    riskUsd: row.risk_usd as number | null,
    riskPct: row.risk_pct as number | null,
    actualRr: row.actual_rr as number | null,
    grossPnl: row.gross_pnl as number | null,
    netPnl: Number(row.net_pnl),
    pnlPct: row.pnl_pct as number | null,
    pnlR: row.pnl_r as number | null,
    mae: row.mae as number | null,
    mfe: row.mfe as number | null,
    fees: row.fees as number | null,
    commission: row.commission as number | null,
    slippage: row.slippage as number | null,
    spreadCost: row.spread_cost as number | null,
    holdingBars: row.holding_bars as number | null,
    durationMs: row.duration_ms as number | null,
    exitReason: row.exit_reason as string | null,
    price: (row.price ?? {}) as Record<string, unknown>,
    risk: (row.risk ?? {}) as Record<string, unknown>,
    performance: (row.performance ?? {}) as Record<string, unknown>,
    duration: (row.duration ?? {}) as Record<string, unknown>,
    volatility: (row.volatility ?? {}) as Record<string, unknown>,
    trend: (row.trend ?? {}) as Record<string, unknown>,
    structure: (row.structure ?? {}) as Record<string, unknown>,
    liquidity: (row.liquidity ?? {}) as Record<string, unknown>,
    smartMoney: (row.smart_money ?? {}) as Record<string, unknown>,
    volumeProfile: (row.volume_profile ?? {}) as Record<string, unknown>,
    breakout: (row.breakout ?? {}) as Record<string, unknown>,
    entryQuality: (row.entry_quality ?? {}) as Record<string, unknown>,
    stop: (row.stop ?? {}) as Record<string, unknown>,
    target: (row.target ?? {}) as Record<string, unknown>,
    filters: (row.filters ?? {}) as Record<string, unknown>,
    news: (row.news ?? {}) as Record<string, unknown>,
    regime: (row.regime ?? {}) as Record<string, unknown>,
    custom: (row.custom ?? {}) as Record<string, unknown>,
    tags: (row.tags ?? []) as string[],
    raw: (row.raw ?? {}) as Record<string, unknown>,
  };
}
