from __future__ import annotations
from typing import Protocol
from .models import BacktestResult
from .jobs import ResearchJob

class ResearchRunRepository(Protocol):
    def save(self, result: BacktestResult) -> None: ...
    def get(self, run_id: str) -> BacktestResult | None: ...

class JobRepository(Protocol):
    def create(self, job_type: str, payload: dict) -> ResearchJob: ...
    def get(self, job_id: str) -> ResearchJob | None: ...
    def update(self, job: ResearchJob, **changes) -> ResearchJob: ...
