/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhookTradingviewRouteImport } from './routes/api/public/webhook/tradingview'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookTradingviewRoute =
  ApiPublicWebhookTradingviewRouteImport.update({
    id: '/api/public/webhook/tradingview',
    path: '/api/public/webhook/tradingview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/settings': typeof SettingsRoute
  '/api/public/webhook/tradingview': typeof ApiPublicWebhookTradingviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/settings': typeof SettingsRoute
  '/api/public/webhook/tradingview': typeof ApiPublicWebhookTradingviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/settings': typeof SettingsRoute
  '/api/public/webhook/tradingview': typeof ApiPublicWebhookTradingviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs' | '/settings' | '/api/public/webhook/tradingview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/settings' | '/api/public/webhook/tradingview'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/settings'
    | '/api/public/webhook/tradingview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicWebhookTradingviewRoute: typeof ApiPublicWebhookTradingviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/tradingview': {
      id: '/api/public/webhook/tradingview'
      path: '/api/public/webhook/tradingview'
      fullPath: '/api/public/webhook/tradingview'
      preLoaderRoute: typeof ApiPublicWebhookTradingviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicWebhookTradingviewRoute: ApiPublicWebhookTradingviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
