/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PendingOrdersRouteImport } from './routes/pending-orders'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhookTradingviewRouteImport } from './routes/api/public/webhook/tradingview'
import { Route as ApiPublicHooksStrategyTickRouteImport } from './routes/api/public/hooks/strategy-tick'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingOrdersRoute = PendingOrdersRouteImport.update({
  id: '/pending-orders',
  path: '/pending-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookTradingviewRoute =
  ApiPublicWebhookTradingviewRouteImport.update({
    id: '/api/public/webhook/tradingview',
    path: '/api/public/webhook/tradingview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStrategyTickRoute =
  ApiPublicHooksStrategyTickRouteImport.update({
    id: '/api/public/hooks/strategy-tick',
    path: '/api/public/hooks/strategy-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/docs': typeof DocsRoute
  '/journal': typeof JournalRoute
  '/pending-orders': typeof PendingOrdersRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/strategy-tick': typeof ApiPublicHooksStrategyTickRoute
  '/api/public/webhook/tradingview': typeof ApiPublicWebhookTradingviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/docs': typeof DocsRoute
  '/journal': typeof JournalRoute
  '/pending-orders': typeof PendingOrdersRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/strategy-tick': typeof ApiPublicHooksStrategyTickRoute
  '/api/public/webhook/tradingview': typeof ApiPublicWebhookTradingviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/docs': typeof DocsRoute
  '/journal': typeof JournalRoute
  '/pending-orders': typeof PendingOrdersRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/strategy-tick': typeof ApiPublicHooksStrategyTickRoute
  '/api/public/webhook/tradingview': typeof ApiPublicWebhookTradingviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/docs'
    | '/journal'
    | '/pending-orders'
    | '/settings'
    | '/api/public/hooks/strategy-tick'
    | '/api/public/webhook/tradingview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/docs'
    | '/journal'
    | '/pending-orders'
    | '/settings'
    | '/api/public/hooks/strategy-tick'
    | '/api/public/webhook/tradingview'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/docs'
    | '/journal'
    | '/pending-orders'
    | '/settings'
    | '/api/public/hooks/strategy-tick'
    | '/api/public/webhook/tradingview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  DocsRoute: typeof DocsRoute
  JournalRoute: typeof JournalRoute
  PendingOrdersRoute: typeof PendingOrdersRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicHooksStrategyTickRoute: typeof ApiPublicHooksStrategyTickRoute
  ApiPublicWebhookTradingviewRoute: typeof ApiPublicWebhookTradingviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-orders': {
      id: '/pending-orders'
      path: '/pending-orders'
      fullPath: '/pending-orders'
      preLoaderRoute: typeof PendingOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/tradingview': {
      id: '/api/public/webhook/tradingview'
      path: '/api/public/webhook/tradingview'
      fullPath: '/api/public/webhook/tradingview'
      preLoaderRoute: typeof ApiPublicWebhookTradingviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/strategy-tick': {
      id: '/api/public/hooks/strategy-tick'
      path: '/api/public/hooks/strategy-tick'
      fullPath: '/api/public/hooks/strategy-tick'
      preLoaderRoute: typeof ApiPublicHooksStrategyTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  DocsRoute: DocsRoute,
  JournalRoute: JournalRoute,
  PendingOrdersRoute: PendingOrdersRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicHooksStrategyTickRoute: ApiPublicHooksStrategyTickRoute,
  ApiPublicWebhookTradingviewRoute: ApiPublicWebhookTradingviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
