/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PendingOrdersRouteImport } from './routes/pending-orders'
import { Route as MarketDataRouteImport } from './routes/market-data'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HandbookRouteImport } from './routes/handbook'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BotRouteImport } from './routes/bot'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandbookIndexRouteImport } from './routes/handbook.index'
import { Route as BacktestIndexRouteImport } from './routes/backtest.index'
import { Route as HandbookVolumeRouteImport } from './routes/handbook.$volume'
import { Route as BacktestSilverBulletRouteImport } from './routes/backtest.silver-bullet'
import { Route as BacktestOrbRouteImport } from './routes/backtest.orb'
import { Route as BacktestCompareRouteImport } from './routes/backtest.compare'
import { Route as BacktestAsianSweepRouteImport } from './routes/backtest.asian-sweep'
import { Route as HandbookVolumeIndexRouteImport } from './routes/handbook.$volume.index'
import { Route as HandbookVolumeStrategyRouteImport } from './routes/handbook.$volume.$strategy'
import { Route as ApiPublicWebhookTradingviewRouteImport } from './routes/api/public/webhook/tradingview'
import { Route as ApiPublicHooksStrategyTickRouteImport } from './routes/api/public/hooks/strategy-tick'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingOrdersRoute = PendingOrdersRouteImport.update({
  id: '/pending-orders',
  path: '/pending-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketDataRoute = MarketDataRouteImport.update({
  id: '/market-data',
  path: '/market-data',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookRoute = HandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookIndexRoute = HandbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HandbookRoute,
} as any)
const BacktestIndexRoute = BacktestIndexRouteImport.update({
  id: '/backtest/',
  path: '/backtest/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookVolumeRoute = HandbookVolumeRouteImport.update({
  id: '/$volume',
  path: '/$volume',
  getParentRoute: () => HandbookRoute,
} as any)
const BacktestSilverBulletRoute = BacktestSilverBulletRouteImport.update({
  id: '/backtest/silver-bullet',
  path: '/backtest/silver-bullet',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestOrbRoute = BacktestOrbRouteImport.update({
  id: '/backtest/orb',
  path: '/backtest/orb',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestCompareRoute = BacktestCompareRouteImport.update({
  id: '/backtest/compare',
  path: '/backtest/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestAsianSweepRoute = BacktestAsianSweepRouteImport.update({
  id: '/backtest/asian-sweep',
  path: '/backtest/asian-sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookVolumeIndexRoute = HandbookVolumeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HandbookVolumeRoute,
} as any)
const HandbookVolumeStrategyRoute = HandbookVolumeStrategyRouteImport.update({
  id: '/$strategy',
  path: '/$strategy',
  getParentRoute: () => HandbookVolumeRoute,
} as any)
const ApiPublicWebhookTradingviewRoute =
  ApiPublicWebhookTradingviewRouteImport.update({
    id: '/api/public/webhook/tradingview',
    path: '/api/public/webhook/tradingview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStrategyTickRoute =
  ApiPublicHooksStrategyTickRouteImport.update({
    id: '/api/public/hooks/strategy-tick',
    path: '/api/public/hooks/strategy-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bot': typeof BotRoute
  '/docs': typeof DocsRoute
  '/handbook': typeof HandbookRouteWithChildren
  '/journal': typeof JournalRoute
  '/market-data': typeof MarketDataRoute
  '/pending-orders': typeof PendingOrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/backtest/asian-sweep': typeof BacktestAsianSweepRoute
  '/backtest/compare': typeof BacktestCompareRoute
  '/backtest/orb': typeof BacktestOrbRoute
  '/backtest/silver-bullet': typeof BacktestSilverBulletRoute
  '/handbook/$volume': typeof HandbookVolumeRouteWithChildren
  '/backtest/': typeof BacktestIndexRoute
  '/handbook/': typeof HandbookIndexRoute
  '/handbook/$volume/$strategy': typeof HandbookVolumeStrategyRoute
  '/handbook/$volume/': typeof HandbookVolumeIndexRoute
  '/api/public/hooks/strategy-tick': typeof ApiPublicHooksStrategyTickRoute
  '/api/public/webhook/tradingview': typeof ApiPublicWebhookTradingviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bot': typeof BotRoute
  '/docs': typeof DocsRoute
  '/journal': typeof JournalRoute
  '/market-data': typeof MarketDataRoute
  '/pending-orders': typeof PendingOrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/backtest/asian-sweep': typeof BacktestAsianSweepRoute
  '/backtest/compare': typeof BacktestCompareRoute
  '/backtest/orb': typeof BacktestOrbRoute
  '/backtest/silver-bullet': typeof BacktestSilverBulletRoute
  '/backtest': typeof BacktestIndexRoute
  '/handbook': typeof HandbookIndexRoute
  '/handbook/$volume/$strategy': typeof HandbookVolumeStrategyRoute
  '/handbook/$volume': typeof HandbookVolumeIndexRoute
  '/api/public/hooks/strategy-tick': typeof ApiPublicHooksStrategyTickRoute
  '/api/public/webhook/tradingview': typeof ApiPublicWebhookTradingviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bot': typeof BotRoute
  '/docs': typeof DocsRoute
  '/handbook': typeof HandbookRouteWithChildren
  '/journal': typeof JournalRoute
  '/market-data': typeof MarketDataRoute
  '/pending-orders': typeof PendingOrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/backtest/asian-sweep': typeof BacktestAsianSweepRoute
  '/backtest/compare': typeof BacktestCompareRoute
  '/backtest/orb': typeof BacktestOrbRoute
  '/backtest/silver-bullet': typeof BacktestSilverBulletRoute
  '/handbook/$volume': typeof HandbookVolumeRouteWithChildren
  '/backtest/': typeof BacktestIndexRoute
  '/handbook/': typeof HandbookIndexRoute
  '/handbook/$volume/$strategy': typeof HandbookVolumeStrategyRoute
  '/handbook/$volume/': typeof HandbookVolumeIndexRoute
  '/api/public/hooks/strategy-tick': typeof ApiPublicHooksStrategyTickRoute
  '/api/public/webhook/tradingview': typeof ApiPublicWebhookTradingviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bot'
    | '/docs'
    | '/handbook'
    | '/journal'
    | '/market-data'
    | '/pending-orders'
    | '/reports'
    | '/settings'
    | '/backtest/asian-sweep'
    | '/backtest/compare'
    | '/backtest/orb'
    | '/backtest/silver-bullet'
    | '/handbook/$volume'
    | '/backtest/'
    | '/handbook/'
    | '/handbook/$volume/$strategy'
    | '/handbook/$volume/'
    | '/api/public/hooks/strategy-tick'
    | '/api/public/webhook/tradingview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bot'
    | '/docs'
    | '/journal'
    | '/market-data'
    | '/pending-orders'
    | '/reports'
    | '/settings'
    | '/backtest/asian-sweep'
    | '/backtest/compare'
    | '/backtest/orb'
    | '/backtest/silver-bullet'
    | '/backtest'
    | '/handbook'
    | '/handbook/$volume/$strategy'
    | '/handbook/$volume'
    | '/api/public/hooks/strategy-tick'
    | '/api/public/webhook/tradingview'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/bot'
    | '/docs'
    | '/handbook'
    | '/journal'
    | '/market-data'
    | '/pending-orders'
    | '/reports'
    | '/settings'
    | '/backtest/asian-sweep'
    | '/backtest/compare'
    | '/backtest/orb'
    | '/backtest/silver-bullet'
    | '/handbook/$volume'
    | '/backtest/'
    | '/handbook/'
    | '/handbook/$volume/$strategy'
    | '/handbook/$volume/'
    | '/api/public/hooks/strategy-tick'
    | '/api/public/webhook/tradingview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BotRoute: typeof BotRoute
  DocsRoute: typeof DocsRoute
  HandbookRoute: typeof HandbookRouteWithChildren
  JournalRoute: typeof JournalRoute
  MarketDataRoute: typeof MarketDataRoute
  PendingOrdersRoute: typeof PendingOrdersRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  BacktestAsianSweepRoute: typeof BacktestAsianSweepRoute
  BacktestCompareRoute: typeof BacktestCompareRoute
  BacktestOrbRoute: typeof BacktestOrbRoute
  BacktestSilverBulletRoute: typeof BacktestSilverBulletRoute
  BacktestIndexRoute: typeof BacktestIndexRoute
  ApiPublicHooksStrategyTickRoute: typeof ApiPublicHooksStrategyTickRoute
  ApiPublicWebhookTradingviewRoute: typeof ApiPublicWebhookTradingviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-orders': {
      id: '/pending-orders'
      path: '/pending-orders'
      fullPath: '/pending-orders'
      preLoaderRoute: typeof PendingOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-data': {
      id: '/market-data'
      path: '/market-data'
      fullPath: '/market-data'
      preLoaderRoute: typeof MarketDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook': {
      id: '/handbook'
      path: '/handbook'
      fullPath: '/handbook'
      preLoaderRoute: typeof HandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook/': {
      id: '/handbook/'
      path: '/'
      fullPath: '/handbook/'
      preLoaderRoute: typeof HandbookIndexRouteImport
      parentRoute: typeof HandbookRoute
    }
    '/backtest/': {
      id: '/backtest/'
      path: '/backtest'
      fullPath: '/backtest/'
      preLoaderRoute: typeof BacktestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook/$volume': {
      id: '/handbook/$volume'
      path: '/$volume'
      fullPath: '/handbook/$volume'
      preLoaderRoute: typeof HandbookVolumeRouteImport
      parentRoute: typeof HandbookRoute
    }
    '/backtest/silver-bullet': {
      id: '/backtest/silver-bullet'
      path: '/backtest/silver-bullet'
      fullPath: '/backtest/silver-bullet'
      preLoaderRoute: typeof BacktestSilverBulletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest/orb': {
      id: '/backtest/orb'
      path: '/backtest/orb'
      fullPath: '/backtest/orb'
      preLoaderRoute: typeof BacktestOrbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest/compare': {
      id: '/backtest/compare'
      path: '/backtest/compare'
      fullPath: '/backtest/compare'
      preLoaderRoute: typeof BacktestCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest/asian-sweep': {
      id: '/backtest/asian-sweep'
      path: '/backtest/asian-sweep'
      fullPath: '/backtest/asian-sweep'
      preLoaderRoute: typeof BacktestAsianSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook/$volume/': {
      id: '/handbook/$volume/'
      path: '/'
      fullPath: '/handbook/$volume/'
      preLoaderRoute: typeof HandbookVolumeIndexRouteImport
      parentRoute: typeof HandbookVolumeRoute
    }
    '/handbook/$volume/$strategy': {
      id: '/handbook/$volume/$strategy'
      path: '/$strategy'
      fullPath: '/handbook/$volume/$strategy'
      preLoaderRoute: typeof HandbookVolumeStrategyRouteImport
      parentRoute: typeof HandbookVolumeRoute
    }
    '/api/public/webhook/tradingview': {
      id: '/api/public/webhook/tradingview'
      path: '/api/public/webhook/tradingview'
      fullPath: '/api/public/webhook/tradingview'
      preLoaderRoute: typeof ApiPublicWebhookTradingviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/strategy-tick': {
      id: '/api/public/hooks/strategy-tick'
      path: '/api/public/hooks/strategy-tick'
      fullPath: '/api/public/hooks/strategy-tick'
      preLoaderRoute: typeof ApiPublicHooksStrategyTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HandbookVolumeRouteChildren {
  HandbookVolumeStrategyRoute: typeof HandbookVolumeStrategyRoute
  HandbookVolumeIndexRoute: typeof HandbookVolumeIndexRoute
}

const HandbookVolumeRouteChildren: HandbookVolumeRouteChildren = {
  HandbookVolumeStrategyRoute: HandbookVolumeStrategyRoute,
  HandbookVolumeIndexRoute: HandbookVolumeIndexRoute,
}

const HandbookVolumeRouteWithChildren = HandbookVolumeRoute._addFileChildren(
  HandbookVolumeRouteChildren,
)

interface HandbookRouteChildren {
  HandbookVolumeRoute: typeof HandbookVolumeRouteWithChildren
  HandbookIndexRoute: typeof HandbookIndexRoute
}

const HandbookRouteChildren: HandbookRouteChildren = {
  HandbookVolumeRoute: HandbookVolumeRouteWithChildren,
  HandbookIndexRoute: HandbookIndexRoute,
}

const HandbookRouteWithChildren = HandbookRoute._addFileChildren(
  HandbookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BotRoute: BotRoute,
  DocsRoute: DocsRoute,
  HandbookRoute: HandbookRouteWithChildren,
  JournalRoute: JournalRoute,
  MarketDataRoute: MarketDataRoute,
  PendingOrdersRoute: PendingOrdersRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  BacktestAsianSweepRoute: BacktestAsianSweepRoute,
  BacktestCompareRoute: BacktestCompareRoute,
  BacktestOrbRoute: BacktestOrbRoute,
  BacktestSilverBulletRoute: BacktestSilverBulletRoute,
  BacktestIndexRoute: BacktestIndexRoute,
  ApiPublicHooksStrategyTickRoute: ApiPublicHooksStrategyTickRoute,
  ApiPublicWebhookTradingviewRoute: ApiPublicWebhookTradingviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
